[Options]
# siehe S.57 f
ms_time_stamp = 0 
us_time_stamp = 1
#defekt
current_range = 0

[Frontend Settings]
# siehe S.60 f
measurement_mode       = 1 
measurement_channel    = 1
current_range_settings = 0
voltage_range_settings = 0

[ExtensionPort Channel Settings]

[Ethernet Configuration]

