[Options]
# siehe S.57 f
ms_time_stamp = 99 
us_time_stamp = 99
current_range = 99

[Frontend Settings]
# siehe S.60 f
measurement_mode       = 99
measurement_channel    = 99
current_range_settings = 99
voltage_range_settings = 99

[ExtensionPort Channel Settings]

[Ethernet Configuration]

[Measurement Configuration]
start_frequency = 99
stop_frequency = 99
step_count = 99


